deployment:
  replicaCount: 2

  container:

    image:
      repository: celeguim/jvminfo
      tag: v10
      pullPolicy: IfNotPresent

    ports:
      http:
        containerPort: 8080

      management:
        containerPort: 9090

    resources:

      requests:
        cpu: 200m
        memory: 256Mi

      limits:
        cpu: "1"
        memory: 512Mi

    probes:

      readiness:
        enabled: true
        path: /actuator/health/readiness
        port: management

      liveness:
        enabled: true
        path: /actuator/health/liveness
        port: management

service:
  type: ClusterIP
  port: 8080
  targetPort: http

autoscaling:
  enabled: true

  minReplicas: 2
  maxReplicas: 5

  cpu:
    targetUtilization: 70

serviceAccount:
  create: true
  name: ""
  