apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: uat
  namespace: argocd
spec:
  description: Workloads exclusivos de UAT
  sourceRepos:
    - 'git@github.com:celeguim/gitops.git'
  destinations:
    - namespace: '*'
      name: uat-cluster1
    - namespace: '*'
      name: uat-cluster2
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
