apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prd
  namespace: argocd
spec:
  description: Workloads exclusivos de PRD
  sourceRepos:
    - 'https://git.example.com/platform/gitops.git'
  destinations:
    - namespace: '*'
      name: prd-cluster1
    - namespace: '*'
      name: prd-cluster2
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
