deployment:
  replicaCount: 2

  container:
    image:
      repository: celeguim/jvminfo
      tag: v3
      pullPolicy: IfNotPresent

    port: 8080

    resources:
      requests:
        cpu: 200m
        memory: 256Mi

      limits:
        cpu: "1"
        memory: 512Mi

    probes:
      readiness:
        enabled: true
        path: /actuator/health/readiness

      liveness:
        enabled: true
        path: /actuator/health/liveness

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

  cpu:
    targetUtilization: 70

serviceAccount:
  create: true
  name: ""
  