deployment:
  replicaCount: 2

  container:

    image:
      repository: celeguim/jvminfo
      tag: v3
      pullPolicy: IfNotPresent

    ports:

      http:
        containerPort: 8080

      management:
        containerPort: 9090

    resources:
      requests:
        cpu: 200m
        memory: 256Mi

      limits:
        cpu: "1"
        memory: 512Mi

    probes:
      readiness:
        enabled: true
        path: /actuator/health/readiness
        port: management
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 3

      liveness:
        enabled: true
        path: /actuator/health/liveness
        port: management


service:
  type: ClusterIP

  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: management
      port: 9090
      targetPort: management

hpa:
  enabled: true

  minReplicas: 2
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
          
serviceAccount:
  create: true
  name: ""
  