################################################################################
# Enterprise Microservice Platform (EMP)
#
# Public API
#
# This file represents the public API of the platform.
#
# Applications SHOULD customize only this file.
#
################################################################################

################################################################################
# Global
################################################################################

nameOverride: ""

fullnameOverride: ""

namespaceOverride: ""

################################################################################
# Deployment
################################################################################

deployment:

  replicaCount: 2

  strategy:

    type: RollingUpdate

  pod:

    annotations: {}

    labels: {}

    nodeSelector: {}

    affinity: {}

    tolerations: []

  container:

    image:

      repository: nginx

      tag: latest

      pullPolicy: IfNotPresent

    resources:

      requests:

        cpu: 200m

        memory: 256Mi

      limits:

        cpu: "1"

        memory: 512Mi

    env: []

    envFrom: []

    probes:

      startup:

        enabled: false

      readiness:

        enabled: true

        path: /actuator/health/readiness

        port: http

        initialDelaySeconds: 10

      liveness:

        enabled: true

        path: /actuator/health/liveness

        port: http

        initialDelaySeconds: 30

################################################################################
# Service
################################################################################

service:

  enabled: true

  type: ClusterIP

  port: 8080

  targetPort: http

  annotations: {}

################################################################################
# Autoscaling
################################################################################

autoscaling:

  enabled: false

  minReplicas: 2

  maxReplicas: 10

  metrics:

    cpu:

      enabled: true

      averageUtilization: 70

    memory:

      enabled: false

      averageUtilization: 80

################################################################################
# Service Account
################################################################################

serviceAccount:

  create: true

  name: ""

  annotations: {}

################################################################################
# Future Features
################################################################################

ingress: {}

monitoring: {}

security: {}

network: {}

rollout: {}
