apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: app2
          env:
            - name: ENVIRONMENT
              value: prd
            - name: LOG_LEVEL
              value: INFO
