apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads-prd
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://git.example.com/platform/gitops.git
              revision: prd
              files:
                - path: clusters/*/*.yaml
          - clusters:
              selector:
                matchLabels:
                  environment: prd
                  cluster-id: '{{ .clusterId }}'
  template:
    metadata:
      name: '{{ .app }}-{{ .clusterId }}'
      namespace: argocd
      labels:
        environment: prd
        cluster-id: '{{ .clusterId }}'
        application: '{{ .app }}'
    spec:
      project: prd
      source:
        repoURL: https://git.example.com/platform/gitops.git
        targetRevision: prd
        path: '{{ .path }}'
      destination:
        name: '{{ .name }}'
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
      revisionHistoryLimit: 10
  syncPolicy:
    applicationsSync: create-update
    preserveResourcesOnDeletion: true
