{{/*
==============================================================================
Enterprise Microservice Platform (EMP)

Deployment

Responsibilities

- Create the Deployment resource
- Configure replica strategy
- Assemble the Pod specification
- Delegate reusable logic to the Helm Library

This template intentionally contains minimal business logic.
==============================================================================*/}}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "microservice.fullname" . }}
  namespace: {{ include "microservice.namespace" . }}

  labels:
{{ include "microservice.labels" . | nindent 4 }}

spec:

  replicas: {{ .Values.deployment.replicaCount }}

  strategy:
    type: {{ .Values.deployment.strategy.type }}

  selector:
    matchLabels:
{{ include "microservice.selectorLabels" . | nindent 6 }}

  template:

    metadata:

      labels:
{{ include "microservice.selectorLabels" . | nindent 8 }}

{{- with .Values.deployment.pod.labels }}
{{ toYaml . | nindent 8 }}
{{- end }}

{{- with .Values.deployment.pod.annotations }}

      annotations:
{{ toYaml . | nindent 8 }}

{{- end }}

    spec:

      serviceAccountName: {{ include "microservice.serviceAccountName" . }}

{{- with .Values.deployment.pod.nodeSelector }}

      nodeSelector:
{{ toYaml . | nindent 8 }}

{{- end }}

{{- with .Values.deployment.pod.affinity }}

      affinity:
{{ toYaml . | nindent 8 }}

{{- end }}

{{- with .Values.deployment.pod.tolerations }}

      tolerations:
{{ toYaml . | nindent 8 }}

{{- end }}

      containers:
{{ include "microservice.container" . | nindent 8 }}