apiVersion: apps/v1
kind: Deployment

metadata:
{{ include "microservice.metadata" . | nindent 2 }}

spec:
  replicas: {{ .Values.deployment.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}

    spec:
      containers:
        - name: app
          image: {{ include "microservice.image" .Values.deployment.container.image | quote }}
          imagePullPolicy: {{ .Values.deployment.container.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.deployment.container.ports.http.containerPort }}
              protocol: TCP

          {{- if .Values.deployment.container.ports.management }}
            - name: management
              containerPort: {{ .Values.deployment.container.ports.management.containerPort }}
              protocol: TCP
          {{- end }}

          resources:
{{ toYaml .Values.deployment.container.resources | indent 12 }}

          {{ include "microservice.httpProbe" (dict
              "type" "readinessProbe"
              "probe" .Values.deployment.container.probes.readiness
          ) | nindent 10 }}

          {{ include "microservice.httpProbe" (dict
              "type" "livenessProbe"
              "probe" .Values.deployment.container.probes.liveness
          ) | nindent 10 }}
