apiVersion: v1
kind: Service

metadata:
{{ include "microservice.metadata" . | nindent 2 }}

spec:
  type: {{ .Values.service.type }}

  selector:
  {{ include "microservice.selector" . | nindent 4 }}

  ports:
  {{ include "microservice.servicePorts" .Values.service.ports | nindent 4 }}
