name: Hello Reusable

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

      repos:
        required: true
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: |
          echo "Hello ${{ inputs.name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Repos: ${{ inputs.repos }}"

      - name: Call Hello Composite Action
        uses: ./.github/actions/hello
        with:
          name: ${{ inputs.name }}
          repos: ${{ inputs.repos }}
